#!/usr/bin/env python3
"""
Single source of truth for wildcard "IP-in-hostname" DNS domains is
/home/www/wildcard-dns-domains.txt. This script regenerates the copies of
that list baked into the Caddyfile, the validator, and the anti-scanner-kit
template, then reloads Caddy and restarts the validator container.

Usage: sudo python3 /home/www/sync-wildcard-domains.py
(sudo needed to reload Caddy / restart the validator container)
"""
import re
import subprocess
import sys

DOMAINS_FILE = "/home/www/wildcard-dns-domains.txt"
MARKER_START = "# BEGIN wildcard-dns-domains"
MARKER_END = "# END wildcard-dns-domains"

TARGETS = [
    "/home/www/Caddyfile",
    "/home/www/validator/server.py",
    "/home/www/validator/test_domains.py",
    "/home/www/anti-scanner-kit/Caddyfile.snippet",
]


def load_domains():
    entries = []
    with open(DOMAINS_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            entries.append(line)
    return entries


def regex_alternation(entries):
    parts = []
    for e in entries:
        if e.endswith("*"):
            base = e[:-1]
            parts.append(re.escape(base) + "[a-z0-9.-]*")
        else:
            parts.append(re.escape(e))
    return "|".join(parts)


def python_tuple_lines(entries):
    lines = []
    for e in entries:
        if e.endswith("*"):
            # validator does plain endswith() matching, not regex -- it can't
            # express a "suffix + any prefix" glob, so glob entries are
            # skipped here (they still apply to the Caddyfile ban/log side).
            continue
        if e == "local-ip.co":
            # the validator's allow-regex only recognizes the real service's
            # exact format (<ip>.my.local-ip.co), so this suffix needs the
            # "my." prefix baked in or the known-good pattern stops matching.
            e = "my.local-ip.co"
        lines.append(f'    "{e}",')
    return lines


def replace_between_markers(text, replacement_lines, indent=""):
    pattern = re.compile(
        re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END), re.DOTALL
    )
    if not pattern.search(text):
        return None
    body = "\n".join(indent + line if line.strip() else line for line in replacement_lines)
    replacement = (
        f"{MARKER_START} (generated by sync-wildcard-domains.py -- edit {DOMAINS_FILE}, not this block)\n"
        f"{body}\n{indent}{MARKER_END}"
    )
    return pattern.sub(lambda _m: replacement, text)


def sync_caddyfile(path, alternation, indent=""):
    with open(path) as f:
        text = f.read()
    lines = [
        f"@wildcard_ip_dns_junk header_regexp Host (?i)(^|\\.)({alternation})(:\\d+)?$",
        "@not_wildcard_ip_dns_junk {",
        f"    not header_regexp Host (?i)(^|\\.)({alternation})(:\\d+)?$",
        "}",
    ]
    new_text = replace_between_markers(text, lines, indent=indent)
    if new_text is None:
        print(f"WARNING: no marker block found in {path}, skipped", file=sys.stderr)
        return False
    if new_text != text:
        with open(path, "w") as f:
            f.write(new_text)
        print(f"updated {path}")
        return True
    return False


def sync_python_file(path, tuple_lines):
    with open(path) as f:
        text = f.read()
    lines = ["WILDCARD_IP_DNS_SUFFIXES = ("] + tuple_lines + [")"]
    new_text = replace_between_markers(text, lines)
    if new_text is None:
        print(f"WARNING: no marker block found in {path}, skipped", file=sys.stderr)
        return False
    if new_text != text:
        with open(path, "w") as f:
            f.write(new_text)
        print(f"updated {path}")
        return True
    return False


def main():
    entries = load_domains()
    if not entries:
        print("no domains found in " + DOMAINS_FILE, file=sys.stderr)
        sys.exit(1)

    alternation = regex_alternation(entries)
    tuple_lines = python_tuple_lines(entries)

    changed = []
    if sync_caddyfile("/home/www/Caddyfile", alternation, indent="    "):
        changed.append("caddyfile")
    if sync_python_file("/home/www/validator/server.py", tuple_lines):
        changed.append("validator")
    sync_python_file("/home/www/validator/test_domains.py", tuple_lines)
    sync_caddyfile("/home/www/anti-scanner-kit/Caddyfile.snippet", alternation)  # template, no reload

    if not changed:
        print("everything already in sync, nothing to do")
        return

    if "caddyfile" in changed:
        subprocess.run(
            ["docker", "compose", "exec", "caddy", "caddy", "validate",
             "--config", "/etc/caddy/Caddyfile"],
            cwd="/home/www", check=True,
        )
        subprocess.run(
            ["docker", "compose", "exec", "caddy", "caddy", "reload",
             "--config", "/etc/caddy/Caddyfile"],
            cwd="/home/www", check=True,
        )
        print("Caddy reloaded")

    if "validator" in changed:
        subprocess.run(
            ["docker", "compose", "restart", "validator"],
            cwd="/home/www", check=True,
        )
        print("validator restarted")


if __name__ == "__main__":
    main()
